
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: possap
  labels:
    app: possap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erp-test
  minReplicas: 1
  maxReplicas: 9
  targetCPUUtilizationPercentage: 70
