apiVersion: v1
kind: Service
metadata:
  name: possap-backend
  labels:
    app: possap-backend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: possap-backend
